### ISSUE TITLE
Docker容器内使用问题

### ISSUE THREAD

**Issue by qingfengfenga** [smartloli/kafka-eagle#446]
kafka版本：2.6.0
Brokers：3
认证方式：SASL Plaintext
加密方式：SCRAM-SHA-256

docker容器内kafka-eagle 出现的问题 
1、jmx
2.0.2 容器内无法连接kafka jmx 端口
容器外可以正常访问。容器内的 1.4.6版本也可以正常访问 jmx

2、kafka sql
容器内 2.0.2 和 1.4.6均无法使用，kafka sql ；
1.4.6报错
```
[2020-12-06 10:14:47] KafkaSqlParser.http-nio-8048-exec-4 - ERROR - Execute sql to query kafka topic has error,msg is Consumer is not subscribed to any topics or assigned any partitions
```
2.0.2报错
```
Failed to construct kafka consumer
```
除了以上问题，容器内其他功暂未发现异常。

以下Dockerfile和docker-compose 来自Docker Hub 的 xuxiangwork
修改版本即可使用，实测支持2.0.2 ，不过以上问题并未解决，可作为测试使用。

```
Dockerfile
FROM java:8-alpine

ENV KE_HOME=/opt/kafka-eagle
ENV EAGLE_VERSION=1.2.6

ADD system-config.properties /tmp
ADD entrypoint.sh /usr/bin

RUN apk --update add wget gettext tar bash sqlite

#get and unpack kafka eagle
RUN mkdir -p /opt/kafka-eagle/conf;cd /opt && \
    wget https://github.com/smartloli/kafka-eagle-bin/archive/v${EAGLE_VERSION}.tar.gz && \
    tar zxvf v${EAGLE_VERSION}.tar.gz -C kafka-eagle --strip-components 1 && \
    cd kafka-eagle;tar zxvf kafka-eagle-web-${EAGLE_VERSION}-bin.tar.gz --strip-components 1 && \
    chmod +x /opt/kafka-eagle/bin/ke.sh && \
    mkdir -p /hadoop/kafka-eagle/db

EXPOSE 8048 8080

ENTRYPOINT ["entrypoint.sh"]

WORKDIR /opt/kafka-eagle
```

```
docker-compose.yml
version: '2'
services:
  kafka-eagle:
    container_name: kafka-eagle
    image: xuxiangwork/kafka-eagle
    ports:
      - "8048:8048"
    environment:
      KAFKA_ZOOKEEPER_HOSTS: <IP:PORT>
      DB_HOST: <IP:PORT>
      DB_USER: <USER>
      DB_PASSWORD: <PASSWORD>
```
