### ISSUE TITLE
不能進入Web UI

### ISSUE THREAD

**Issue by gogovan-vincentngai** [smartloli/kafka-eagle#485]
安裝背景
- K8S Cluster
- Kafka Cluster strimzi

安裝文件
Dockerfile
```
FROM openjdk:8-alpine3.9

ENV KE_HOME=/opt/kafka-eagle
ENV EAGLE_VERSION=1.4.6

COPY entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh
RUN sed -i 's#dl-cdn.alpinelinux.org#mirrors.aliyun.com#g' /etc/apk/repositories && \
    apk --update add wget gettext tar bash sqlite && \
    apk cache clean ; rm -rf /var/cache/apk/* && \
    mkdir /opt/kafka-eagle -p && cd /opt && \
    wget https://github.com/smartloli/kafka-eagle-bin/archive/v${EAGLE_VERSION}.tar.gz && \
    tar zxvf v${EAGLE_VERSION}.tar.gz -C kafka-eagle --strip-components 1 && rm -f v${EAGLE_VERSION}.tar.gz && \
    cd kafka-eagle;tar zxvf kafka-eagle-web-${EAGLE_VERSION}-bin.tar.gz --strip-components 1 && rm -f kafka-eagle-web-${EAGLE_VERSION}-bin.tar.gz  && \
    chmod +x /opt/kafka-eagle/bin/ke.sh && \
    mkdir -p /hadoop/kafka-eagle/db



EXPOSE 8048 8080

ENTRYPOINT ["/usr/bin/entrypoint.sh"]

WORKDIR /opt/kafka-eagle
```

entrypoint.sh

```
#!/bin/bash
bash /opt/kafka-eagle/bin/ke.sh start
sleep 3
tail -f /opt/kafka-eagle/logs/log.log
```

kafka-eagle.yaml
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-eagle
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app : kafka-eagle
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app : kafka-eagle
    spec:
      containers:
      - image: gogotechhk/gogox-public-image:kafka-eagle1.4.6-4
        imagePullPolicy: Always
        name: kafka-eagle
        ports:
        - containerPort: 8048
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /opt/kafka-eagle/conf
          name: conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 256
          name: kafka-eagle-config
          optional: false
        name: conf
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-eagle-client
spec:
  ports:
    - name: http
      port: 8048
      targetPort: 8048
  selector:
    app : kafka-eagle
```

system-config.properties
```
######################################
# multi zookeeper&kafka cluster list
######################################
kafka.eagle.zk.cluster.alias=cluster1
cluster1.zk.list=vincent-cluster-zookeeper-client:2181

######################################
# zk client thread limit
######################################
kafka.zk.limit.size=25

######################################
# kafka eagle webui port
######################################
kafka.eagle.webui.port=8048

######################################
# kafka offset storage
######################################
cluster1.kafka.eagle.offset.storage=kafka

######################################
# enable kafka metrics
######################################
kafka.eagle.metrics.charts=true
kafka.eagle.sql.fix.error=true

######################################
# kafka sql topic records max
######################################
kafka.eagle.sql.topic.records.max=5000

######################################
# alarm email configure
######################################
kafka.eagle.mail.enable=false

######################################
# delete kafka topic token
######################################
kafka.eagle.topic.token=keadmin

######################################
# kafka sasl authenticate
######################################
cluster1.kafka.eagle.sasl.enable=true
cluster1.kafka.eagle.sasl.protocol=SASL_PLAINTEXT
cluster1.kafka.eagle.sasl.mechanism=SCRAM-SHA-512
cluster1.kafka.eagle.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=kfadmin password=Xbth7R8FVD7m

######################################
# kafka jdbc driver address
######################################
kafka.eagle.driver=com.mysql.jdbc.Driver
kafka.eagle.url=jdbc:mysql://ke-mysql:3306/kafka-eagle
kafka.eagle.username=root
kafka.eagle.password=mysql
```

測試
kubectl port-forward po/kafka-eagle-7767d75cd-9dnx9 -n vincent 8048:8048

Log
<img width="1070" alt="Screenshot 2021-03-10 at 11 47 34 AM" src="https://user-images.githubusercontent.com/35673973/110573596-7e5c7c80-8196-11eb-9955-e42631d4fa4d.png">
<img width="1439" alt="Screenshot 2021-03-10 at 11 47 41 AM" src="https://user-images.githubusercontent.com/35673973/110573607-82889a00-8196-11eb-94a0-1276b3673432.png">

所有密碼確定可以使用
似乎是 kafka-eagle 只接受local ip ?
